# Generated by Django 4.0.4 on 2022-06-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='Identificação Rede')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('class_icon', models.CharField(max_length=50, verbose_name='Classe CSS do ícone')),
                ('url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ['key'],
            },
        ),
    ]
